//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectWith中佑.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlotGameWebEntities2 : DbContext
    {
        public SlotGameWebEntities2()
            : base("name=SlotGameWebEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackMember> BackMembers { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameRecord> GameRecords { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberShop> MemberShops { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ServeProblem> ServeProblems { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
